### ISSUE TITLE
2 scrollbars on MacOS Chrome

### ISSUE THREAD

**Issue by dnish** [rommguy/react-custom-scroll#10]
Hey,
if I start scrolling, I can see two scrollbars (the customized and the native one). On Windows everything works fine, the issue only happens on MacOS Chrome.

The native one then hides again if I stop scrolling.

**Comment by rommguy** [comment]
Hi!
Glad you are using this.
Can you also check if you see 2 scrollbars when you open my demo on MacOS Chrome ?
[Here is the link](http://rommguy.github.io/react-custom-scroll/example/demo.html)

I'm guessing there is something wrong in the overflow properties. 
Can you send me a link to your project code, or to the page itself ?

**Comment by dnish** [comment]
Yep,
was an overflow issue. BTW: Maybe we should add

   -webkit-overflow-scrolling: touch;

to the wrapper's class. Otherwise the scrolling on iOS devices isn't smooth.

**Comment by AnarH93** [comment]
Hi all, I have the same problem on my macOS with Chrome.

I checked and removed all overflow properties on parent blocks, add the max-height rule, but still have 2 scrolls.

here is an [online demo](http://predictoria.com/), look at Predictions block.

![untitled](https://user-images.githubusercontent.com/5373730/36854278-46626a26-1d79-11e8-8656-912d11e7633b.png)
