### ISSUE TITLE
stop click event propagation when clicking on scroll handle

### ISSUE THREAD

**Issue by havlasme** [rommguy/react-custom-scroll#105]
Hello,

I've encountered an issue, that when scroll handle is positioned over element, that has onClick event callback it is executed when I click on scroll handle. Is there a way how to avoid this issue?

Thanks

**Comment by rommguy** [comment]
Sure, it's possible but usually means you have a UI problem - there should always be a margin between the edge of your content and the edge of the screen - the scrollbar shouldn't cover actionable buttons. 

I also want to keep the behavior of this component the same as the native scroll. 
What happens when you click on the native scroll bar?

**Comment by havlasme** [comment]
I understand your point, the native scroll bar is located "outside" so clicking on it does nothing. However in my case the scrollbar is positioned over existing elements, therefore for user point of view clicking on scrollbar handle should not trigger onClick callback of element positioned behind it.

What I'm trying to do is implement behavior similar to what facebook ui does, when you click on messenger icon, the contact list is opened and it is scrollable - the scrollbar is positioned over actionable buttons, but you can't activate them by clicking, when the scrollbar is drawn over them.

I'd like that functionality to be part of your library, but if you are not interesting supporting that I'll understand and find a workaroud.

**Comment by rommguy** [comment]
I don't mind adding that as a prop. Something like "blockClickOnHandle" - boolean
But how will users click on the actionable buttons if the handle is blocking them?

You are welcome to create a PR adding that prop, it shouldn't be complicated
Please also add a test for that. 

The current onClick starts like this - 
```js
if (!this.hasScroll || !this.isMouseEventOnCustomScrollbar(event) || this.isMouseEventOnScrollHandle(event)) {
      return
    }
```
You can stop the event of isMouseEventOnScrollHandle returns true

**Comment by havlasme** [comment]
Ok. I'll look into that. Well the handle is blocking only a minor part of the actionable button (see attached screenshot)

![Screenshot from 2021-07-23 22-09-19](https://user-images.githubusercontent.com/6549693/126836104-549d8b0e-1aac-41f2-93e9-0792d01047ad.png)

**Comment by rommguy** [comment]
Nice, NP, if you'll create a PR I'll merge it
Maybe you can avoid it with padding-left 20px on the content
