### ISSUE TITLE
can't reproduce firstComp example in codesandbox

### ISSUE THREAD

**Issue by fbegue** [rommguy/react-custom-scroll#108]
I've pretty much remade the entire example in codesandbox, but the custom scroll bars just aren't there

https://codesandbox.io/s/react-custom-scroll-firstcomp-example-broken-q809g

In my own first attempt, I couldn't get onScroll to fire so I'm definitely not understanding something here:
https://codesandbox.io/s/react-custom-scroll-broken-q48e7

Why can't I reproduce the example, and why does my attempt just not function at all?

**Comment by rommguy** [comment]
Hi,
I'll try to help. 
The sandbox in the first link is broken - I see an error related to babel

About the second link sandbox: 
You need some element of your own, inside CustomScroll to limit the height of content with max-height, or alternatively, use relative height to parent.
In your example there is only a P element under CustomScroll, with height 1200px. Take a look at the [demo](http://rommguy.github.io/react-custom-scroll/example/demo.html) page I created for CustomScroll - you will see that I have an element with max-height: 525px, limiting the content, and that is the element I wrapped with CustomScroll.
CustomScroll's job isn't to limit the content, just to allow you to design the scroll. It can't know what is the limit you want to give.

**Comment by fbegue** [comment]
Sorry about babel error, fixed that here:
https://codesandbox.io/s/react-custom-scroll-firstcomp-example-broken-q809g?file=/src/FirstComp.js

> You need some element of your own, inside CustomScroll to limit the height of content with max-height <

I see you doing that with this rule on the content inside the custom scroll element with
` .panel-content-custom {max-height: 425px;}`

but that isn't making the CustomScroll show up. I elaborated in the comments there further by following you 3 steps you listed below. 

Sorry what your saying makes sense but it's not working

**Comment by rommguy** [comment]
I found your problem. 
In the Readme you can find this statement - 
"In both cases you have to include the customScroll.css file in your page."

You're missing the css file from CustomScroll package. Once you will import it everything will work.

**Comment by rommguy** [comment]
@fbegue Please let me know if importing the css fixed the issue.

**Comment by fbegue** [comment]
hey @rommguy that worked - I'm not sure how I forgot that on that example, I did that on the other one (!?)

thanks

**Comment by rommguy** [comment]
Cool, closing issue
