### ISSUE TITLE
warning " > react-custom-scroll@4.3.0" has unmet peer dependency "prop-types@*".

### ISSUE THREAD

**Issue by tjx666** [rommguy/react-custom-scroll#110]
I'm using Typescript to develop react project. So, prop-types is useless for me, but the warning is so annoying.

![image](https://user-images.githubusercontent.com/41773861/144166203-23cf7ca7-064f-433a-ac6b-b0be7c2cd62a.png)

**Comment by rommguy** [comment]
Removed peer dependency prop-types in V7
