### ISSUE TITLE
Wheel doesnt work while focusing on the thumb element

### ISSUE THREAD

**Issue by namnm** [rommguy/react-custom-scroll#12]
When I put my mouse hover on the thumb/bar element, and try to wheel, it doesnt scroll. One solution for this is that we trigger the event from thumb/bar to the content section. I have implemented it for myself like this, and it works perfect, hope this helps.
Ps: `this.to` is a version of jQuery.scrollTo implementation.

```js
  handleBarWheel(e) {
    if (e.deltaY === 0) {
      this.to(this.contentTop)
      return
    }
    // clone the nativeEvent and dispatch to contentDOMNode
    // this only works in webkit engine
    if (BrowserAgent.isWebkit) {
      const nativeEvent = e.nativeEvent
      const newEvent = new nativeEvent.constructor(nativeEvent.type, nativeEvent)
      const contentPrevTop = this.contentTop
      this.contentDOMNode.dispatchEvent(newEvent)
      if (contentPrevTop === this.contentTop) {
        e.preventDefault()
        e.stopPropagation()
      } else {
        newEvent.preventDefault()
        newEvent.stopPropagation()
      }
      return
    }
    // update scroll manually if we can not dispatch the new event
    let delta = e.deltaY
    let shouldUseAnimation = false
    // if it's not firefox trackpad OSX, we recalculate the delta
    if (!BrowserAgent.isMozila || e.deltaMode) {
      const isReversedDirection = this.pendingWheel && this.pendingWheel * delta < 0
      if (isReversedDirection) {
        this.pendingWheel = 0
      }
      this.pendingWheel += (delta < 0 ? -1 : 1)
      if (this.pendingWheel > MAX_PENDING_WHEEL) {
        this.pendingWheel = MAX_PENDING_WHEEL
      } else if (this.pendingWheel < -MAX_PENDING_WHEEL) {
        this.pendingWheel = -MAX_PENDING_WHEEL
      }
      delta = this.pendingWheel * WHEEL_SPEED
      shouldUseAnimation = true
    }
    const contentNewTop = this.contentTop + delta
    if (this.to(contentNewTop, shouldUseAnimation)) {
      e.preventDefault()
      e.stopPropagation()
    }
  }
```

**Comment by rommguy** [comment]
Hi @namnm , 
Thanks for using this component, and I really appreciate you opened an issue on this problem.

Regarding the solution you suggested, I've tested the first part, and it does not work, the new wheel event is created with 'isTrusted' false, causing the OS to ignore it and not scroll. This leads to the second part of your solution, where you infer from the wheel event the new scroll value.

I really tried to avoid creating scroll events myself from wheel events, since the conversion is very browser & OS specific, and always has bugs in it. 
It should also be maintained when versions change. 


I think a better solution will be to use pointer-events:none on the custom scroll area, and infer the event target in the parent (outer-container)
I'll try to work it out

**Comment by rommguy** [comment]
@namnm I would love to know what you think about the solution

**Comment by namnm** [comment]
`pointer-events: none` is not good, we can not click on the thumb/bar or drag the thumb to scroll to a new position.
I tested my solution on latest Chome, Safari, Firefox, Opera, IE10, on both trackpad and mouse. It does work. I have known about `isTrusted` false, in Firefox the new event can not be dispatched, but in webkit engine, it works well.

**Comment by namnm** [comment]
Ok I have just looked at your solution around `pointer-event: none` problem I talked about. It's clever, hehe.
Actually my target has some different purposes with yours:
- I want to animate the scroll when click on bar, and it will scroll to the exactly point we click, not scroll by a fixed amount.
- I want the outside component, can manipulate the scroll via `to` method, example you make a custom dropdown, and want to use key to navigate between value...

In fact all of those purposes can be achieved using your solution, but at least I must implement the `to` method. You hack on recalculation of the mouse event, I hack on dispatch / simulate the wheel event. We are all good, haha.

Nice to know you on this.
Ps: I have just found a new bug on your demo when I resize the screen, but it's hard to describe. I will try to do a screen record and open a new issue.

**Comment by rommguy** [comment]
Thanks for the feedback!
When I created this component, I really tried to created exactly the native scroll behavior, just with a custom design... 
Now I understand what you are trying to accomplish
I tried to play with interpreting the wheel event to a scroll amount, and saw that it is a complicated thing, and best left alone :)

Looking forward to the new bug :)

BTW, I'd appreciate if you star this repository on github

**Comment by pa-nam** [comment]
Starred <3
