### ISSUE TITLE
findDOMNode is deprecated in StrictMode

### ISSUE THREAD

**Issue by Mae6e** [rommguy/react-custom-scroll#120]
Hi.
I use this code in JSX:

`const CustomScrollbar = (props) => {
  return (
    <CustomScroll>
      {props.children}
    </CustomScroll>
  )
}`

and my Sidebar Component:
`        <CustomScrollbar >
            <div className="sidebar_inner" data-simplebar >
                   .......
            </div>
        </CustomScrollbar>`

but, when I clicked the content with the scrollbar I had this error in the console.
how can I resolve it?
error:
"findDOMNode is deprecated in StrictMode. findDOMNode was passed an instance of S which is inside StrictMode. Instead, add a ref directly to the element you want to reference"
![image](https://user-images.githubusercontent.com/19348884/198280414-49a2d433-c402-4749-8323-d0ce2a8f2d46.png)

**Comment by rommguy** [comment]
Thanks @maede71 for opening the issue
I'll work on a new version without findDOMNode and will release it soon
