### ISSUE TITLE
Produces "React Minified Error" when used with vite 4 in production with minify enabled

### ISSUE THREAD

**Issue by bh0mbalziyad** [rommguy/react-custom-scroll#127]
I recently migrated a project from CRA to Vite 4 and found routes/components which used react-custom-scroll were triggering my error boundary.

Here's the error

<img width="1789" alt="image" src="https://user-images.githubusercontent.com/24297205/215406292-dced07d5-f44b-41f0-9dc8-4a96d601c909.png">

After searching online I've found that this is a common issue with Vite due to rollup having issues dealing with packages that use module.exports

Is there any roadmap to release an ES6 version of this package?

**Comment by rommguy** [comment]
Sounds like a reasonable request. I'll do some try to get to it.
If you can create a PR that would be great as I'm not sure when I'll find the time for it

**Comment by rommguy** [comment]
Just released a whole rewrite of the infra, moved to Vite.
Please switch to v7
