### ISSUE TITLE
Document Browser Support

### ISSUE THREAD

**Issue by reintroducing** [rommguy/react-custom-scroll#17]
This looks great, thanks for your work on it. Could you add actual browser support to the readme rather than just "cross browser"? It'd be great to know every browser supported at quick glance without having to test them all when trying to incorporate into a project.

**Comment by rommguy** [comment]
Glad you like it !
Actually, it is really **cross** browser :)
I do not know any browser where React works, and this doesn't, including mobile
Do you think writing that would be enough or should I actually list them ?
I just don't want to miss one from the list, and people will think it is not supported

**Comment by reintroducing** [comment]
I think if its truly cross browser and you've tested lets say all the way down to IE9 then you should just list that its IE9+ (unless of course you tested 8 and it worked there too, etc).  It would just give people reassurance that they can start using this with knowing that its supported in their required browsers without testing themselves (though I'd still strongly urge people to test themselves anyway just to make sure).
