### ISSUE TITLE
Is there scrolltoBottom option?

### ISSUE THREAD

**Issue by gsudhesh** [rommguy/react-custom-scroll#19]
How to acheive the scrolltoBottom option when the content area is dynamically increased,

**Comment by rommguy** [comment]
Can you give more details on what you are trying to do?
Do you mean with react props, or by finding the scrolled dom node and setting a scroll position ?

**Comment by gsudhesh** [comment]
![modal](https://cloud.githubusercontent.com/assets/10115880/19508771/acd31832-95f8-11e6-975d-0ac79ed4ea51.png)

After adding the item inside the container, then  the scroll should always move to bottom position.

**Comment by lucidlive** [comment]
The biggest use case I could see for this is a chat window. Every time a message is added, you scroll to bottom.

**Comment by rommguy** [comment]
@gsudhesh is this still relevant ?
I have some time now to add more functionality

**Comment by ohana54** [comment]
@gsudhesh @lucidlive I'm going to try to work on it, will add a "keepAtBottom" prop that will keep the scroll position at bottom, assuming it was there before (meaning if the user scrolled up, and then content was added, it won't scroll back down).

**Comment by rommguy** [comment]
Deployed in version 1.10.0
