### ISSUE TITLE
is it possible to fire event when scroll to bottom ?

### ISSUE THREAD

**Issue by yonaichin** [rommguy/react-custom-scroll#20]
Trying to implement infinite scroll to load more content.
Is there anyway to trigger event when scroll to bottom?

Tried [react-waypoint](https://github.com/brigade/react-waypoint) but failed.
It seems that ``` <Waypoint /> ``` component unable to trigger in ``` <CustomScroll /> ```

Here's the code
```
import React from 'react'
import CustomScroll from 'react-custom-scroll'
import Waypoint from 'react-waypoint'


import Thumbnail from 'components/Thumbnail'

export const Photo = ({ dataset }) => {
  const Thumbnails = _.map(dataset, (data, idx) => {
    return (
      <Thumbnail {...data} key={idx}/>
    )
  })

  const onWaypointEnter = () => {
    console.log('onWaypointEnter')
  }

  return (
    <CustomScroll>
      <div className={classes.thumbnail_container}>
        { Thumbnails }
        <Waypoint onEnter={onWaypointEnter}/>
      </div>
    </CustomScroll>
  )
}

export default Photo

```

Thanks in advance.

**Comment by patrykcieszkowski** [comment]
There is 'onScroll' attribute, so you can bind the event to your custom method and and calculate it.

**Comment by rommguy** [comment]
@yonaichin is onScroll good enough for you ?
Can I close this issue ?

**Comment by yonaichin** [comment]
Sorry about this late reply. 'onScroll' function works perfectly. Thanks for the help.
