### ISSUE TITLE
scrollTo

### ISSUE THREAD

**Issue by jakeaaron** [rommguy/react-custom-scroll#21]
Hey! First off, great work on this! 

Second, I was wondering if there is (or will be) a scroll to option? Before I had wrapped certain lists with this component, I was handing them off to a function I wrote to set the scrollTop value to scroll the list on a keychange, but it appears since wrapping them the element.scrollTop = calculatedValue doesn't work...

Any help would be appreciated! (and lemme know if you need a code example or something)

**Comment by rommguy** [comment]
I think it can be added, is the value a number ?

**Comment by jakeaaron** [comment]
I would think so! I'm thinking of a couple of existing apis like scrollTo and scrollTop and they just take integer values.

I appreciate the response!

**Comment by rommguy** [comment]
No problem, I'll try to add it

**Comment by rommguy** [comment]
@jakeaaron you can use v1.9.0 that includes scrollTo prop.
Enjoy

**Comment by jakeaaron** [comment]
Awesome! Thanks so much! Thank you for the quick response and action! +1 😄
