### ISSUE TITLE
React 15.5 warnings

### ISSUE THREAD

**Issue by renatho** [rommguy/react-custom-scroll#24]
Will you update to support react 16? React 15.5 is firing the deprecation warnings of proptype and createClass.
More info: [React v15.5.0](https://facebook.github.io/react/blog/2017/04/07/react-v15.5.0.html)

**Comment by rommguy** [comment]
Sure, on it

**Comment by rommguy** [comment]
@renatho Do you think it is reasonable to require propTypes as a peer dependency like I did with React and ReactDOM ?

**Comment by renatho** [comment]
Hi @rommguy! For React and ReactDOM I think it is good, because the developer will use it in his project.
But for the PropTypes, although it is a good practice, the developer should not necessarily use it in his project.
I would install it like a dev dependency (because it is not used in prod).

**Comment by renatho** [comment]
Hi @rommguy!
To help you, I updated the code to resolve React 15.5 deprecation warnings: #27

**Comment by rommguy** [comment]
Thanks @renatho,
The way you solved it won't work - if someone doesn't have propTypes package the code will break.
if I write this -  require('prop-types'), I actually make everyone who use custom-scroll to include propTypes in their package.json
So it looks like I have to give up on the propTypes...
I'm considering another solution - doing it in a try-catch block, and only running the try-catch if React is in development mode. 
What do you think ?

**Comment by renatho** [comment]
Hi @rommguy!
Well noted! I verified in other react components and everyone is adding it like normal dependency. I will update it to a normal dependency ;)
I believe it solves!
