### ISSUE TITLE
Performance and component update

### ISSUE THREAD

**Issue by qoalu** [rommguy/react-custom-scroll#28]
I am looking into making my UI snappier and dug into the perf tools of react

![image](https://cloud.githubusercontent.com/assets/1624045/26051768/7af9c4aa-3963-11e7-8d8c-187ae38a5ba9.png)
![image](https://cloud.githubusercontent.com/assets/1624045/26051926/18e40680-3964-11e7-9249-6f362f8deee8.png)

I am using custom scroll on a list component which is updated when an item is added. 
One particular component sticks out and it's called "t". 

I am sure that CustomScroll is also called "t", but it's weird that the custom scroll wrapping the updating component ( highlighted in blue on the screen) does not seem to be the culprit here and updates quite fast. The other one on the right (separated from the call stack) is causing a 200ms delay on each action.
Is it the the same Custom Scroll "t" or should I look into other parts of my app? If it is custom Scroll, what is causing this delay and can we reduce it somehow?

**Comment by qoalu** [comment]
Removing customScroll removed t from the stack. Why could this be happening?

**Comment by qoalu** [comment]
I did some googling and it looks like the Layout can be caused by certain uses of JS instructions.
Probably one of those:
https://gist.github.com/paulirish/5d52fb081b3570c81e3a

**Comment by rommguy** [comment]
Sorry, I had a busy time, I'll try to investigate this week

**Comment by rommguy** [comment]
Sorry @qoalu, I can't see a way in which I avoid accessing element scrollHeight - I need it to calculate the size of the scroll handle and it's position. 
I can suggest a different solution - I can add a prop, that will prevent all calculations in customScroll didUpdate method. It means that while that prop equals true, the scroll won't work properly.
This can be used in case you know you have a performance sensitive flow going on, that doesn't require scrolling, and when it is over you can change the prop value to false. It can also be used to tell the custom scroll that the content isn't dynamic, so it should only calculate sizes once when it mounts. 
What do you think?
