### ISSUE TITLE
keepAtBottom doesn't work if the size of the inner element doesn't change

### ISSUE THREAD

**Issue by Neglexis** [rommguy/react-custom-scroll#30]
Scenario:
I have a chatcomponent that shows only the latest 50 chats in a conversation. If all my chat lines have the same height and a new line is added (which causes the previous line 0 to disappear and adds a new line on index 49), the component doesn't scroll down.

I've tried editing [this line](https://github.com/rommguy/react-custom-scroll/blob/gh-pages/src/main/customScroll.js#L94) so that it compares `this.props.children` with `prevProps.children`, but doesn't always work because for some reason the `reachedBottomOnCurrentRender` evaluates to false..

Any idea?

Currently I just copied your code and removed the `reachedBottomOnCurrentRender` which still makes the component behave as expected, so not sure what the use of that check is?

**Comment by rommguy** [comment]
@Neglexis I'm not sure I understand the scenario - the content changes but the total size stays the same, and for some reason the scroll goes up ?
Can you please commit a failing test ?

**Comment by rommguy** [comment]
Hmmm, I think I understand.
Well, if the size of content didn't change, the scroll position should stay the same.
If they scroll is at bottom when you change the content of the array, does the scroll position go up somehow?
Or do you mean that when you change the content you want the scroll to go to the bottom even if it wasn't previously at the bottom, as a response to the change ?

**Comment by Neglexis** [comment]
Actually, what you describe, is indeed the behaviour I would expect.

But line 94 actually counters this
`} else if (this.props.keepAtBottom && contentResized && reachedBottomOnPrevRender && !reachedBottomOnCurrentRender) {`

Notice the `contentResized`? Well, if it didn't resize, it won't call the `this.updateScrollPosition(this.contentHeight - this.visibleHeight)` in the next line.

**Comment by Neglexis** [comment]
Definitely not option 1, since that would go directly against the `keepAtBottom` prop.
Option 2 is the one I would expect, but currently doesn't happen.

The new line gets added, but the component doesn't scroll to it. I have to scroll to bottom again, even though `keepAtBottom` is enabled.

**Comment by rommguy** [comment]
ok, got it, I'm checking

**Comment by Neglexis** [comment]
FYI, this is currently the `componentDidUpdate` that currently satisfies my needs

```
  componentDidUpdate(prevProps, prevState) {
    const prevContentHeight = this.contentHeight;
    const prevVisibleHeight = this.visibleHeight;
    const innerContainer = this.getScrolledElement();
    const reachedBottomOnPrevRender = prevState.scrollPos >= prevContentHeight - prevVisibleHeight;

    this.contentHeight = innerContainer.scrollHeight;
    this.scrollbarYWidth = innerContainer.offsetWidth - innerContainer.clientWidth;
    this.visibleHeight = innerContainer.clientHeight;
    this.scrollRatio = this.contentHeight ? this.visibleHeight / this.contentHeight : 1;

    this.toggleScrollIfNeeded();

    if (this.props.freezePosition || prevProps.freezePosition) {
      this.adjustFreezePosition(prevProps);
    }
    if (typeof this.props.scrollTo !== 'undefined' && this.props.scrollTo !== prevProps.scrollTo) {
      this.updateScrollPosition(this.props.scrollTo);
    } else if (
      this.props.keepAtBottom &&
      this.props.children !== prevProps.children &&
      reachedBottomOnPrevRender
    ) {
      this.updateScrollPosition(this.contentHeight - this.visibleHeight);
    }
  }
```

I removed both `contentResized` and `reachedBottomOnCurrentRender` though :)

**Comment by rommguy** [comment]
I'm unable to reproduce
Can you paste the JSX where you render CustomScroll ?

**Comment by rommguy** [comment]
@Neglexis Thanks for showing me this bug. The fix is in version 2.0.2
I've added a failing test, you are welcome to review it.  

I used your code to fix the issue with one change - I think comparing props.children isn't the best way to check what we need - if the render is a result of an external change or not.
Someone could cache the props from outside, and pass the same reference to them, and this will fail.
Instead I created a variable called "externalRender", assigned true in willReceiveProps (only invoked when render is caused by external action), and assigned false at the end of didUpdate
This way I can enforce the bottom position as long as the render is a result of an external change, regardless of size changes in the content.

**Comment by rommguy** [comment]
@Neglexis Does the fix work for you?

**Comment by Neglexis** [comment]
Sorry for the late answer @rommguy but that indeed appears to have solved it, thanks a bunch!

**Comment by rommguy** [comment]
@Neglexis Excellent, I would appreciate if you could star this repo, thanks

**Comment by Neglexis** [comment]
@rommguy Consider it done!
