### ISSUE TITLE
Prop to start the scroll at bottom

### ISSUE THREAD

**Issue by Neglexis** [rommguy/react-custom-scroll#31]
Would there be any possibility to pass in a prop that sets the initial scrolling position all the way to the bottom.

I know there is the `scrollTo` property, but that requires a number, while I just want it to be all the way to the bottom.

**Comment by rommguy** [comment]
Maybe use scrollTo={Number.MAX_SAFE_INTEGER} ?

**Comment by rommguy** [comment]
@Neglexis can I close this one ?

**Comment by Neglexis** [comment]
@rommguy Sure, we stopped using this plugin because it wasn't exactly fitting our needs

**Comment by rommguy** [comment]
@Neglexis ok thanks, good luck
