### ISSUE TITLE
Scroll animation

### ISSUE THREAD

**Issue by De-Santa** [rommguy/react-custom-scroll#32]
Hi! Thanks for great component! 
Wondering how I can animate scroll? Im trying to build anchor-scroll and was thinking about react-motion but I can only pass scroll coordinates to `scrollTo` prop which is not best idea. Can you provide some help with this? Thanks!

**Comment by bozskejkaja** [comment]
Would you mind sharing how you solved this, @De-Santa ? I'm in a similar situation myself.
