### ISSUE TITLE
How to make if mouse move inactive, hide scrollbar

### ISSUE THREAD

**Issue by smartameer** [rommguy/react-custom-scroll#33]
By default when I'm on a view area, it shows up the scroll, if my mouse is inactive for some time, can we hide the scroll?

**Comment by rommguy** [comment]
Hi, I'm glad you're using this component.

It shouldn't be too complicated. You can use this.hasScroll to implement it.
And add a mouseMove listener to innerContainer that displays the scroll if it is hidden

Can you create a pull request ?

**Comment by rommguy** [comment]
@smartameer what do you say ?

**Comment by rommguy** [comment]
Closed since no response from @smartameer
