### ISSUE TITLE
Implementing scrollToElement?

### ISSUE THREAD

**Issue by eleweek** [rommguy/react-custom-scroll#34]
Would it be difficult to implement scrollToElement? I need this and I'd love to send a PR, but can't quite wrap my head around how I could implement this. (Any tips would be appreciated!)

**Comment by rommguy** [comment]
Hi, no problem, I'll be happy to help. 
Can you please give a use case with some more details ?
do you know the element's y position ?
How do you reference it ?

**Comment by eleweek** [comment]
Hi, I am currently not quite sure how to do this. I guess I could calculate the element y position, but I am not sure what would be the best way to pass it back.

**Comment by rommguy** [comment]
One of the props is scrollTo which takes a number for the scroll position.
So you can use that one.
You have a ref on the element you want to scroll to ?

**Comment by rommguy** [comment]
@eleweek Anything new with this issue ?

**Comment by rommguy** [comment]
Closed due to lack of info
