### ISSUE TITLE
'keepAtBottom' not working when onClick event is triggered

### ISSUE THREAD

**Issue by tompere** [rommguy/react-custom-scroll#42]
it seems that `keepAtBottom="true"` is not working when onClick event is triggered. namely, when the content is dynamic and changes as a result of onClick invocation.

as a **workaround** - using `event.stopPropagation();` in onClick fixed it.

```jsx
<CustomScroll>
  {list.map(item => (<div onClick={/* do something that causes `list` to re-render */}></div>) )}
</CustomScroll>
```

**Comment by sag1v** [comment]
Can you post a working example that reproduce the issue?
it is working for me as well as [in this example](http://rommguy.github.io/react-custom-scroll/example/demo.html?dynamic=true).

**Comment by rommguy** [comment]
@sag1v I can reproduce it. I will commit a failing test tomorrow, hopefully with a solution
