### ISSUE TITLE
Class names should be more unique or assignable

### ISSUE THREAD

**Issue by orangecoloured** [rommguy/react-custom-scroll#43]
I would advise changing class names that are used to something more unique. Or even make them customisable. For example these are pretty common and can be already used in any kind of a project: `outer-container`, `inner-container`, `content-wrapper`.

That's what I encountered. The script just doesn't work because those already have assigned height, width, etc.

**Comment by rommguy** [comment]
@orangecoloured thanks for opening the issue, you are right.
Any chance you can create a PR for this ?

**Comment by orangecoloured** [comment]
Not sure yet. Fixing it now. Will get back to you later when I make it work :)

**Comment by orangecoloured** [comment]
@rommguy So, I've got it working. Had to make a bit of refactoring so it would properly pass linting. Probably it's going to be a little bit messy. Anyway, you'll have a look for yourself when I submit it. Gonna do it today. Thanks for the package btw, it's really cross-browser.

**Comment by orangecoloured** [comment]
@rommguy https://github.com/rommguy/react-custom-scroll/pull/45

**Comment by rommguy** [comment]
Looks like an excellent improvement, thanks!
I'll review and merge in the next few days.

**Comment by orangecoloured** [comment]
@rommguy, did you have time to review my PR? Are you going to merge it anytime soon or do you want anything changed/fixed beforehand?

**Comment by rommguy** [comment]
Hi @orangecoloured 
I reviewed some of the code and wrote comments in your PR page
All the style changes are a problem, can you try to keep the current style (spaces, semi colons etc.)
Also one syntax mistake - 6x instead of 6px

About the logic - 
You added a prop "cssPrefix" but it looks like if someone used it, the entire functionality will break, since all the css selectors will stop working. 
How do you solve that ?

**Comment by orangecoloured** [comment]
@rommguy 
Sorry, didn't see your reply.
I've made a little fix and answered the prefix question.

**Comment by orangecoloured** [comment]
@rommguy Would you like me to fix the css issue?
I can make the styling to be inline instead of using external css rules.

**Comment by sag1v** [comment]
This is a critical issue in my opinion.

**Comment by sag1v** [comment]
I'm trying to play with it but i get errors when i try to run `build` or `sassex`:

>react-custom-scroll\node_modules\minimatch\minimatch.js:116:11)
>     throw new TypeError('glob pattern string required')

`npm run develop` works with no errors.

@orangecoloured have you encountered similar issue?

**Comment by orangecoloured** [comment]
@sag1v are you building from my PR or the master branch?
I had to fix all the syntax errors to make the build.

**Comment by sag1v** [comment]
@orangecoloured i forked the master branch

**Comment by orangecoloured** [comment]
@sag1v yeah, then you'll get a huge amount of errors making the build. I think there are two ways of solving this. Either remove this linting from the build process or make the code to comply with its rules. I chose the second way, as I thought there was some reasoning for having that linter there.

**Comment by sag1v** [comment]
This is not a linting error though. 
Just in case, I removed `npm run lint` from the `build` script and still get the same error.
It is probably something to do with minimatch and sass.

@rommguy Do you have an idea what's that all about?

**Comment by sag1v** [comment]
I think the issue related to windows or mac / linux when runing `postcss`.
https://github.com/postcss/postcss-cli/issues/34
https://github.com/milligram/milligram/issues/122

when i remove the `sassex` from the `build` script, it builds fine with no errors.

@orangecoloured on which OS are you?

**Comment by orangecoloured** [comment]
@sag1v linux.

**Comment by sag1v** [comment]
I posted a PR #51 using the css-module solution.

@orangecoloured i hope you don't mind 😃

**Comment by orangecoloured** [comment]
@sag1v not at all.

**Comment by sag1v** [comment]
@orangecoloured Cool.
Now i hope @rommguy will be ok with this and merge ASAP as we can't use this great library at the moment. 🙏

**Comment by rommguy** [comment]
Hi guys, 
I'll probably merge it in the next few days.
I will also separate the example build from the build script, so you won't have any trouble running the build script. 
@orangecoloured the eslint errors are something related to your environment. I don't have any errors when running eslint on the project, that's one of the reasons I didn't want to merge the first PR.
