### ISSUE TITLE
.handleDrag class should be added on the root element (.custom-scroll)

### ISSUE THREAD

**Issue by michalrusina** [rommguy/react-custom-scroll#5]
this way it would be possible to add user-select: none to the container and prevent selecting the content WHILE scrolling. also i would suggest to change the class name to handle-drag (ocd:)

**Comment by rommguy** [comment]
Thanks, sounds good

**Comment by rommguy** [comment]
@michalrusina Now the selection doesn't happen while you drag, but for some reason when you release the mouse the content becomes selected. Any idea how to block this ?
