### ISSUE TITLE
unpkg cdn is targeting an old version 

### ISSUE THREAD

**Issue by sag1v** [rommguy/react-custom-scroll#52]
After #51 and [this commit](https://github.com/rommguy/react-custom-scroll/commit/680187103bbd6f1997cbdfa0d23382e1d090d907)  we need to update the unpkg cdn  in the readme file.
Now they reference `3.2.0` version but they should reference `4.0.0`.
With that said, i think we can do it with `@latest` so it will always ref to the latest version.
```
* [Js file](https://unpkg.com/react-custom-scroll@latest/dist/reactCustomScroll) 
* [css file](https://unpkg.com/react-custom-scroll@latest/dist/customScroll.css)    
```
Will produce: 
* [Js file](https://unpkg.com/react-custom-scroll@latest/dist/reactCustomScroll) 
* [css file](https://unpkg.com/react-custom-scroll@latest/dist/customScroll.css) 
  
What do you think?

**Comment by rommguy** [comment]
Thank you, you're right. I've updated the Readme
I would recommend against using latest - it means that breaking changes in this component will probably break your app

**Comment by sag1v** [comment]
@rommguy make sense
