### ISSUE TITLE
Main entry in package.json points to untranspiled file

### ISSUE THREAD

**Issue by egidijusj** [rommguy/react-custom-scroll#57]
Main entry in `package.json` points to `./index.js` which is not transpiled (contains keyword `const`) and will break consumer app in old browsers.

It could be fixed by pointing main to `./dist/reacCustomScroll` or simply re-exporting required component in index.js:
```
module.exports = require('./dist/reactCustomScroll')
```

**Comment by rommguy** [comment]
Hi @egidijusj, Thanks for opening an issue!
Your suggestion is already the case in index.js
What do you think is the cause for this issue ?
