### ISSUE TITLE
addEventListener should be with passive:false

### ISSUE THREAD

**Issue by matveyok** [rommguy/react-custom-scroll#62]
Since Chrome 73 events are passive by default.
When adding new events need to pass `{ passive: false}` to enable the usage of `preventDefault` here:
https://github.com/rommguy/react-custom-scroll/blob/e603ae20e2592476a521a93407cae481e223627a/src/main/customScroll.js#L247-L248

Reference:
https://www.chromestatus.com/features/6662647093133312
https://developers.google.com/web/updates/2017/01/scrolling-intervention

**Comment by supromikali** [comment]
Confirm the issue.

Chrome console produces warnings on scroll otherwise like follows
`
[Intervention] Unable to preventDefault inside passive event listener due to target being treated as passive. See https://www.chromestatus.com/features/6662647093133312
`

**Comment by supromikali** [comment]
Hello, @rommguy ! First of all, thank you for this awesome plugin! Is there a chance to merge a fix for this issue with scroll intervention? Looks like a quick and safe improvement

**Comment by rommguy** [comment]
Hi @supromikali and @matveyok 
I finally have some time for this open source project, expect this fix in the next few days. 
Sorry it took so long
