### ISSUE TITLE
does not work

### ISSUE THREAD

**Issue by eeeman1** [rommguy/react-custom-scroll#71]
<CustomScroll>
  your content
</CustomScroll> 

does not work, no scroll appeared

**Comment by rommguy** [comment]
Hi @eeeman1 
Glad you're using this tool.
Can you provide more info? 
Can you please check the [demo](http://rommguy.github.io/react-custom-scroll/example/demo.html) page and see if you see the custom scroll there?

**Comment by eeeman1** [comment]
"@zeit/next-sass": "^1.0.1",
    "isomorphic-fetch": "^2.2.1",
    "js-cookie": "^2.2.0",
    "next": "^9.0.2",
    "next-cookies": "^1.1.2",
    "next-redux-wrapper": "^3.0.0-alpha.3",
    "node-sass": "^4.12.0",
    "react": "^16.8.6",
    "react-custom-scroll": "^4.1.3",
    "react-dom": "^16.8.6",
    "react-redux": "^7.1.0",
    "redux": "^4.0.4"


import CustomScroll from 'react-custom-scroll';

<CustomScroll>
  your content
</CustomScroll>

**Comment by eeeman1** [comment]
I'm sorry, I did not connect the css file, I thought it was already included in the custom scroll component

**Comment by rommguy** [comment]
Cool. @eeeman1 I'd appreciate it if you could star this repo
