### ISSUE TITLE
no horizontal scroll

### ISSUE THREAD

**Issue by eeeman1** [rommguy/react-custom-scroll#72]
vertical scrolling works fine, there’s just no horizontal scrolling

    "@zeit/next-sass": "^1.0.1",
    "isomorphic-fetch": "^2.2.1",
    "js-cookie": "^2.2.0",
    "next": "^9.0.2",
    "next-cookies": "^1.1.2",
    "next-redux-wrapper": "^3.0.0-alpha.3",
    "node-sass": "^4.12.0",
    "react": "^16.8.6",
    "react-custom-scroll": "^4.1.3",
    "react-dom": "^16.8.6",
    "react-redux": "^7.1.0",
    "redux": "^4.0.4"

import CustomScroll from 'react-custom-scroll';

`
                        <div style={{height: '200px'}}>
                            <CustomScroll>
                               here wide content
                            </CustomScroll>
                        </div>
`

**Comment by rommguy** [comment]
Hi @eeeman1. 
This library does not support horizontal scroll. Sorry
