### ISSUE TITLE
Chrome Mouse Wheel preventDefault problem

### ISSUE THREAD

**Issue by Mickyt1038** [rommguy/react-custom-scroll#73]
using chrome, on mouse wheel scroll, i'm getting an error '[Intervention] Unable to preventDefault inside passive event listener due to target being treated as passive'.  If we remove line 288 and 291 in blockOuterScroll function within customScroll.js the problem seems to be fixed. Chrome v #77

**Comment by morulus** [comment]
The same error has occurred. The used version is 4.1.3. Easily reproduced in Chrome 76.0.3809.132

**Comment by rommguy** [comment]
Hi guys, thanks, I'm checking

**Comment by rommguy** [comment]
Related to this React issue - https://github.com/facebook/react/issues/14856

**Comment by rommguy** [comment]
Fixed in https://github.com/rommguy/react-custom-scroll/commit/9f51cdae2802e52c23ac749e7d4510ab40f108d3

**Comment by Mickyt1038** [comment]
Superb, cheer rommguy

**Comment by rommguy** [comment]
@Mickyt1038 , @morulus , I'd appreciate it if you can star this repo, thanks
