### ISSUE TITLE
Your example of '<customScroll>...' uses camel-case, which does not comply with JSX

### ISSUE THREAD

**Issue by ArielDKenan** [rommguy/react-custom-scroll#8]
JSX has a convention in which lowercase tags are considered to be primitives, and so they are transformed into React.createElement('customScroll', ...). "Otherwise, there would be namespace collisions and no way for us to determine if the user intended to insert a component or a DOM node."

I could not get this component working until I tried "{ CustomScroll } = require('react-custom-scroll')" and used < CustomScroll > and it suddenly worked! It is working great now, thank you.

**Comment by rommguy** [comment]
Fixed the README, I was using React-templates until now instead of JSX, and the problem does not exists there. 
Switched to JSX now...
Sorry for the trouble

**Comment by rommguy** [comment]
@ArielDKenan I would appreciate a start on this repo :)
