### ISSUE TITLE
Typescript types definitions

### ISSUE THREAD

**Issue by rvdende** [rommguy/react-custom-scroll#84]
Hi I had the issue where typescript was complaining about missing types. 

Theres another types defnition for `react-custom-scrollbars` but not for `react-custom-scroll`
So I made one as a workaround and thought I'd share it here.  Link to gist: https://gist.github.com/rvdende/8292424f64e028dff9dc2c5deb43a9a6

**Comment by rommguy** [comment]
Amazing! thanks a lot

**Comment by rommguy** [comment]
@rvdende - I created a PR for DefinitelyTyped to add your types.
I added you as a writer. 
Thanks again.

**Comment by rvdende** [comment]
Excellent! Much apprecitated :) keep up the good work
