### ISSUE TITLE
CRA project @babel/plugin-proposal-class-properties not enabled

### ISSUE THREAD

**Issue by navalex** [rommguy/react-custom-scroll#85]
I'm using create-react-app to build my ReactJS project, and after installed and add your component inside my app, I got this babel error:

`SyntaxError: node_modules\react-custom-scroll\src\main\customScroll.js: Support for the experimental syntax 'classProperties' isn't currently enabled (97:21):`

And actually we can't really edit RCA webpack/babel config, so I tried to use CRACO (https://github.com/gsoft-inc/craco) and I created this file at project root:

craco.config.js
```
module.exports = {
    babel: {
        "plugins": [
            ["@babel/plugin-proposal-class-properties", {"loose": true}]
        ]
    }
}
```

but it does change nothing after restart `npm start`, so I wanted to know if is there any workaround ?

Thanks.

**Comment by rommguy** [comment]
Hi @navalex,
Thank you for using this component. Sorry it took me a long time to get to this issue, I had a lot of pressure at work. 
I used this component without problems with CRA and as far as I know it should work. 
Tomorrow I'll try to reproduce this issue and let you know what I found

**Comment by rommguy** [comment]
Hi again @navalex,
I just created a Create-react-app project from scratch and added react-custom-scroll
I'm getting no errors. 

Can you please write which version of react-scripts you have in your project?

**Comment by rommguy** [comment]
Hi @navalex,
I found the problem causing this error in issue #89 . You can take a look to see how to fix it.
I'm closing this issue.
If the solution to #89 doesn't work for you, feel free to reopen this issue.
Thanks and enjoy
