### ISSUE TITLE
I don't see the the scroll handle container and the handle himself

### ISSUE THREAD

**Issue by thijs666** [rommguy/react-custom-scroll#86]
I don't see the the scroll handle container and the handle himself. Any idea how I can fix this?

Normally it should show up here right?
https://gyazo.com/89d4d4b3448282740f22ef7811f9572c

```
import React from 'react'
import PropTypes from 'prop-types'
import { StaticQuery, graphql } from 'gatsby'

import Header from './header'
import NavMenu from './nav-menu'
import CustomScroll from 'react-custom-scroll';
import '../styles/customScroll.css';

import "../styles/main.css"
import "../styles/grid.css"

class Layout extends React.Component {
  state = {
    active: false,
  }

  toggleSidebar = () => {
    this.setState({ active: !this.state.active })
  };

  render() {
    const { children } = this.props
    const { active } = this.state
    return (
      <StaticQuery
        query={graphql`
          query SiteTitleQuery {
            site {
              siteMetadata {
                title
              }
            }
          }
        `}
        render={data => (
            <>
            <Header siteTitle={data.site.siteMetadata.title}
              active={active}
              toggleSidebar={this.toggleSidebar}
            />
            <NavMenu
              active={active}
              toggleSidebar={this.toggleSidebar}
            />
            <CustomScroll
            allowOuterScroll={true}
            >
              <div className="scroll-wrapper">
                <main>{children}</main>
                </div>
            </CustomScroll>
          </>
        )}
      />
    )
  }
}

Layout.propTypes = {
  children: PropTypes.node.isRequired,
}

export default Layout
```

**Comment by rommguy** [comment]
Hi, thanks for using this package.
It looks like the custom scroll styles are not present. 
Please make sure you follow the instructions in the readme - 

1. You need to load the customScroll.css file in your page 
2. You need to remove any overflow properties from your content root component (the div with 'scroll-wrapper' in your case)

If you still see the problem, I'd be happy to take a look if you can post a link to your page here

**Comment by thijs666** [comment]
Hi Guy,

Thanks for your fast response. 

1. The customScroll.css is loaded correctly.
2. The scroll-wrapper has no style. So it shouldn't have any overflow properties

So I'm still seeing this problem. Glad that you want to look at it! I builded the newest version to netlify, so you can access it.
The link is: https://webspek.netlify.app

It is getting late here, so I'll catch some sleep and look with some new energy tomorrow. Those scroll-plugins are killing me haha.

Thanks in advance,

Thijs

**Comment by rommguy** [comment]
I looked a the page - I don't see a height limit anywhere - if there is no height limit there is no scroll, all the content is visible by default. 
Did you mean to limit the view to 100vh or something like that?

**Comment by thijs666** [comment]
Yes the view should be 100vh. So I should add a height-limit?

**Comment by rommguy** [comment]
The best way to add a custom scroll is to create your app without it, make sure you see scroll in the correct places and everything works.
Then add the custom scroll and just remove the overflow property from your own container.

**Comment by rommguy** [comment]
@thijs666 thanks for closing, I hope everything worked out.
Please start this repo if you can, I would appreciate it
