### ISSUE TITLE
Failure to Compile

### ISSUE THREAD

**Issue by I2obiN** [rommguy/react-custom-scroll#89]
![image](https://user-images.githubusercontent.com/7683830/85213741-6a4bc300-b35a-11ea-81ee-0d2bf10870fc.png)

These are my dependencies for package.json
    "@date-io/date-fns": "^1.3.13",
    "@material-ui/core": "^4.8.0",
    "@material-ui/icons": "^4.5.1",
    "@material-ui/pickers": "^3.2.8",
    "axios": "^0.19.0",
    "bootstrap": "^4.4.1",
    "date-fns": "^2.8.1",
    "draft-js": "^0.11.5",
    "draft-js-export-html": "^1.4.1",
    "node-sass": "^4.14.1",
    "react": "^16.12.0",
    "react-app-polyfill": "^1.0.6",
    "react-custom-scroll": "^4.2.0",
    "react-dom": "^16.12.0",
    "react-router-dom": "^5.1.2",
    "react-scripts": "^3.4.1",
    "react-select": "^3.0.8",
    "react-transition-group": "^4.4.1",
    "reactstrap": "^8.2.0",
    "typeface-roboto": "0.0.54"

**Comment by rommguy** [comment]
Looks like a duplicate of #85. Am I right?

**Comment by rommguy** [comment]
Is it possible you somehow take the source code instead of the babel compiled code?

**Comment by I2obiN** [comment]
Yeh looks like a duplicate. I just ran npm install as per readme

**Comment by rommguy** [comment]
Did it work? no build errors?

**Comment by I2obiN** [comment]
![image](https://user-images.githubusercontent.com/7683830/85231744-abdb7d00-b3f1-11ea-8924-5812df9a3f3f.png)

**Comment by rommguy** [comment]
Yep, I'm aware of the vulnerability, but other then that - did you manage to build and render your app?

**Comment by I2obiN** [comment]
Oh yeh app built fine, when I drop the element into code I get the error. It's inside a reactstrap modal.

**Comment by rommguy** [comment]
I can't understand, sorry.
You render CustomScroll, after you import it from your node modules right?
The error you pasted above is during the npm install stage, but is a warning, it does not break the npm install.
When you render your code with CustomScroll, do you see another error?

**Comment by I2obiN** [comment]
Yep. Sorry when you asked did it work I thought you meant the npm install. When I render CustomScroll I see the error in my first comment.

**Comment by rommguy** [comment]
NP. 
How do you import CustomScroll in your code?
Can you paste the import line here?
The correct way is to install it with npm - 
`npm install react-custom-scroll`
and then import it like so - 
`import` CustomScroll from 'react-custom-scroll'`

I know the npm install shows a warning, it shouldn't stop you, and I'll fix it in the next version

**Comment by I2obiN** [comment]
![image](https://user-images.githubusercontent.com/7683830/85232897-c0704300-b3fa-11ea-92f8-9bf8d85e635e.png)

![image](https://user-images.githubusercontent.com/7683830/85232855-61aac980-b3fa-11ea-8757-0584e471e0e2.png)

**Comment by rommguy** [comment]
ok, cool, we found the problem! 
You shouldn't import from /src folder, you should import the already compiled version.
Replace the import line in your code with this - 
`````js
import CustomScroll from 'react-custom-scroll'
`

**Comment by I2obiN** [comment]
Ah thanks. Working now, much appreciated dude 👍

**Comment by rommguy** [comment]
Excellent! glad to hear
I would appreciate it if you could star this repo.

In general - don't import src files from npm packages, only the exported compiled files.

**Comment by rommguy** [comment]
@I2obiN I just published version 4.2.1 that fixes the vulnerability you saw when installing with npm
