### ISSUE TITLE
Please add documentation for adding custom class for scroll bar 

### ISSUE THREAD

**Issue by raj01104** [rommguy/react-custom-scroll#9]
Unable to find related documentation for custom scroll bar for. please add the same

**Comment by rommguy** [comment]
@raj01104 I've updated the Readme, please let me know if it helped

**Comment by raj01104** [comment]
@roomguy Thanks for update. It helped

**Comment by rommguy** [comment]
@raj01104 Glad I could help, I would appreciate it if you could star this repository.
Thanks
